---
- name: Install QEMU support libraries for Debian distributions
  ansible.builtin.apt:
    name:
      - binfmt-support
      - qemu-user-static
  become: true
  when: ansible_pkg_mgr == "apt" and deb_distro_base == "debian"

- name: Install Qemu for Alpine distributions
  become: true
  community.general.apk:
    name:
      - qemu
      - qemu-img
  when: ansible_pkg_mgr == "apk"

- name: Install Qemu for FreeBSD
  become: true
  community.general.pkgng:
    name: qemu
  when: ansible_system == "FreeBSD"

- name: Install QEMU for Linux
  ansible.builtin.package:
    name: "{{ 'qemu-kvm' if ansible_pkg_mgr == 'apt' else 'qemu' }}"
  become: true
  when: ansible_system == "Linux" and ansible_pkg_mgr != "apk"

- name: Install QEMU for MacOS
  community.general.homebrew:
    name: qemu
  when: ansible_system == "Darwin"

- name: Install QEMU for Windows
  community.windows.win_scoop:
    name: qemu
  when: ansible_system == "Win32NT"

- name: Install Quickemu for Linux
  ansible.builtin.get_url:
    dest: "/usr/local/bin/{{ item }}"
    mode: "755"
    owner: root
    url: >-
      https://raw.githubusercontent.com/wimpysworld/quickemu/master/{{ item }}
  become: true
  loop:
    - macrecovery
    - quickemu
    - quickget
  when: ansible_system == "Linux"
