---
- name: Install JJUI for FreeBSD
  become: true
  community.general.pkgng:
    name: jjui
  tags:
    - install
  when: ansible_system == "FreeBSD"

- name: Get latest JJUI version for Linux
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/jjui.json
  register: jjui_formula
  tags:
    - install
  when: ansible_system == "Linux"

- name: Create JJUI temporary directory for Linux
  ansible.builtin.tempfile:
    state: directory
  register: jjui_temp
  tags:
    - install
  when: ansible_system == "Linux"

- name: Set JJUI temporary directory permissions for Linux
  ansible.builtin.file:
    mode: "755"
    path: "{{ jjui_temp.path }}"
    state: directory
  tags:
    - install
  when: ansible_system == "Linux"

- name: Download JJUI for Linux
  ansible.builtin.unarchive:
    dest: "{{ jjui_temp.path }}"
    mode: "777"
    remote_src: true
    src: >-
      https://github.com/idursun/jjui/releases/download/v{{
      jjui_formula.json.versions.stable }}/jjui-{{
      jjui_formula.json.versions.stable }}-linux-{{ system_architecture }}.zip
  tags:
    - install
  when: ansible_system == "Linux"

- name: Install JJUI for Linux
  ansible.builtin.copy:
    dest: /usr/local/bin/jjui
    force: true
    mode: "755"
    remote_src: true
    src: >-
      {{ jjui_temp.path }}/jjui-{{ jjui_formula.json.versions.stable }}-linux-{{
      system_architecture }}
  become: true
  tags:
    - install
  when: ansible_system == "Linux"

- name: Install JJUI for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: jjui
  tags:
    - install
  when: ansible_system == "Darwin"

- name: Install JJUI for Windows
  community.windows.win_scoop:
    global: true
    name: jjui
  tags:
    - install
  when: ansible_system == "Win32NT"

- name: Create JJUI settings directory for Unix
  ansible.builtin.file:
    group: "{{ group_id }}"
    mode: "755"
    owner: "{{ user_id }}"
    path: "{{ user_home }}/.config/jjui"
    state: directory
  become: true
  tags:
    - config
  when: ansible_system != "Win32NT"

- name: Copy JJUI settings file for Unix
  ansible.builtin.copy:
    dest: "{{ user_home }}/.config/jjui/config.toml"
    force: true
    group: "{{ group_id }}"
    mode: "644"
    owner: "{{ user_id }}"
    src: config.toml
  become: true
  tags:
    - config
  when: ansible_system != "Win32NT"

- name: Create JJUI settings directory for Windows
  ansible.windows.win_file:
    path: "{{ user_home }}\\AppData\\Roaming\\jjui"
    state: directory
  tags:
    - config
  when: ansible_system == "Win32NT"

- name: Copy JJUI settings file for Windows
  ansible.windows.win_copy:
    dest: "{{ user_home }}\\AppData\\Roaming\\jjui\\config.toml"
    force: true
    src: config.toml
  tags:
    - config
  when: ansible_system == "Win32NT"

- name: Remove JJUI temporary directory for Linux
  ansible.builtin.file:
    path: "{{ jjui_temp.path }}"
    state: absent
  tags:
    - install
  when: ansible_system == "Linux"
