---
- name: Install GitLab Runner for Alpine
  become: true
  community.general.apk:
    name: gitlab-runner
  when: ansible_pkg_mgr == "apk"

- name: Install GitLab Runner for Arch
  become: true
  community.general.pacman:
    name: gitlab-runner
  when: ansible_pkg_mgr == "pacman" and system_architecture == "amd64"

- name: Install GitLab Runner for Debian
  ansible.builtin.apt:
    deb: >-
      https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_{{
      system_architecture }}.deb
  become: true
  when: ansible_pkg_mgr == "apt"

# Gitlab runner Arm64 DNF package is broken.
- name: Add GitLab GPG key for Fedora and Suse
  ansible.builtin.rpm_key:
    key: https://packages.gitlab.com/runner/gitlab-runner/gpgkey/runner-gitlab-runner-49F16C5CC3A0F81F.pub.gpg
  become: true
  when: ansible_pkg_mgr in ["dnf", "zypper"] and system_architecture == "amd64"

- name: Install GitLab Runner for Fedora
  ansible.builtin.dnf:
    name: >-
      https://gitlab-runner-downloads.s3.amazonaws.com/latest/rpm/gitlab-runner_{{
      system_architecture }}.rpm
  become: true
  when: ansible_pkg_mgr == "dnf" and system_architecture == "amd64"

- name: Install GitLab Runner for FreeBSD
  become: true
  community.general.pkgng:
    name: gitlab-runner
  when: ansible_system == "FreeBSD"

- name: Install GitLab Runner for MacOS
  community.general.homebrew:
    name: gitlab-runner
  when: ansible_system == "Darwin"

- name: Install GitLab Runner for Suse
  become: true
  community.general.zypper:
    name: >-
      https://gitlab-runner-downloads.s3.amazonaws.com/latest/rpm/gitlab-runner_{{
      system_architecture }}.rpm
  when: ansible_pkg_mgr == "zypper"

- name: Install GitLab Runner for Windows
  community.windows.win_scoop:
    name: gitlab-runner
  when: ansible_system == "Win32NT"
