---
python_applications:
  - "jinja2-cli[toml,yaml,xml]"
  - cookiecutter
  - name: jupyterlab
    extras:
      - bokeh
      - librosa
      - numpy
      - polars
      - scipy
      - soundfile
      - torch
  - name: marimo[sandbox,sql]
    extras:
      - altair
      - nbformat
      - pytest
      - ruff
      - ty
  - ruff
  - ty
