---
- name: Get latest Cargo Binstall version for Windows
  ansible.windows.win_uri:
    method: GET
    return_content: true
    url: https://api.github.com/repos/ryankurte/cargo-binstall/releases/latest
  register: rust_binstall_release

- name: Install Rust for Windows
  community.windows.win_scoop:
    name: rustup-msvc

- name: Update Rust for Windows
  ansible.windows.win_shell: |
    rustup self update
    rustup update stable
  environment:
    CARGO_HOME: "{{ scoop_apps }}\\rustup-msvc\\current\\.cargo"
    Path: >-
      {{ scoop_apps }}\\rustup-msvc\\current\\.cargo\\bin;{{ ansible_env.Path }}
  failed_when: >-
    rust_update.rc != 0 and 'update is disabled' not in rust_update.stderr
  register: rust_update

- name: Add Rust components for Windows
  ansible.windows.win_command: rustup component add {{ item }}
  environment:
    CARGO_HOME: "{{ scoop_apps }}\\rustup-msvc\\current\\.cargo"
    Path: >-
      {{ scoop_apps }}\\rustup-msvc\\current\\.cargo\\bin;{{ ansible_env.Path }}
  loop: "{{ rust_components }}"

- name: Add Rust targets for Windows
  ansible.windows.win_command: rustup target add {{ item }}
  environment:
    CARGO_HOME: "{{ scoop_apps }}\\rustup-msvc\\current\\.cargo"
    Path: >-
      {{ scoop_apps }}\\rustup-msvc\\current\\.cargo\\bin;{{ ansible_env.Path }}
  loop: "{{ rust_targets }}"

- name: Download Cargo Binstall archive for Windows
  ansible.windows.win_get_url:
    dest: "{{ ansible_env.TEMP }}/cargo_binstall.zip"
    url: >-
      https://github.com/ryankurte/cargo-binstall/releases/download/{{
      cargo_binstall_release.json.tag_name
      }}/cargo-binstall-x86_64-pc-windows-msvc.zip

- name: Decompress Cargo Binstall archive for Windows
  community.windows.win_unzip:
    dest: "{{ ansible_env.TEMP }}/cargo_binstall"
    src: "{{ ansible_env.TEMP }}/cargo_binstall.zip"

- name: Create Cargo Binstall directory for Windows
  ansible.windows.win_file:
    dest: "{{ scoop_apps }}/rustup-msvc/current/.cargo/bin"
    state: directory

- name: Install Cargo Binstall for Windows
  ansible.windows.win_copy:
    dest: "{{ scoop_apps }}/rustup-msvc/current/.cargo/bin/cargo-binstall.exe"
    remote_src: true
    src: "{{ ansible_env.TEMP }}/cargo_binstall/cargo-binstall.exe"

- name: Update or install Cargo packages for Windows
  ansible.windows.win_command: cargo binstall --no-confirm {{ item }}
  environment:
    CARGO_HOME: "{{ scoop_apps }}\\rustup-msvc\\current\\.cargo"
    Path: >-
      {{ scoop_apps }}\\rustup-msvc\\current\\.cargo\\bin;{{ ansible_env.Path }}
  loop: "{{ cargo_applications }}"
