---
- name: Install Firefox for Debian
  ansible.builtin.apt:
    name: firefox-esr
  become: true
  when: ansible_pkg_mgr == "apt" and deb_distro_base == "debian"

- name: Install Firefox for FreeBSD
  become: true
  community.general.pkgng:
    name: firefox
  when: ansible_system == "FreeBSD"

- name: Install Firefox for Linux
  ansible.builtin.package:
    name: firefox
  become: true
  when: >-
    ansible_system == "Linux" and (ansible_pkg_mgr != "apt" or deb_distro_base
    != "debian")

- name: Install Firefox for MacOS
  community.general.homebrew_cask:
    accept_external_apps: true
    name: firefox
    state: present
  when: ansible_system == "Darwin"

- name: Install Firefox for Windows
  community.windows.win_scoop:
    name: firefox
  when: ansible_system == "Win32NT"

- name: Find default Firefox profile for Unix
  firefox_default_profile: {}
  register: firefox_profile_unix
  when: ansible_system != "Win32NT"

- name: Find default Firefox profile for Windows
  win_firefox_default_profile: {}
  register: firefox_profile_windows
  when: ansible_system == "Win32NT"

- name: Copy Firefox user preferences for Unix
  ansible.builtin.copy:
    dest: "{{ firefox_profile_unix['path'] }}/user.js"
    force: true
    mode: "600"
    owner: "{{ ansible_user_id }}"
    src: user.js
  when: ansible_system != "Win32NT"

- name: Copy Firefox user preferences for Windows
  ansible.windows.win_copy:
    dest: "{{ firefox_profile_windows['path'] }}/user.js"
    src: user.js
  when: ansible_system == "Win32NT"
