---
- name: Install Fish for FreeBSD
  become: true
  community.general.pkgng:
    name: fish
  when: ansible_system == "FreeBSD"

- name: Install Fish for Linux
  ansible.builtin.package:
    name: fish
  become: true
  when: ansible_system == "Linux"

- name: Install Fish for MacOS
  community.general.homebrew:
    name: fish
  when: ansible_system == "Darwin"

- name: Create Fish configuration directory for Unix
  ansible.builtin.file:
    mode: "755"
    owner: "{{ ansible_user_id }}"
    path: "{{ ansible_env.HOME }}/.config/fish"
    state: directory
  when: ansible_system != "Win32NT"

- name: Create Fish completions directory for Unix
  ansible.builtin.file:
    mode: "755"
    owner: "{{ ansible_user_id }}"
    path: "{{ ansible_env.HOME }}/.config/fish/completions"
    state: directory
  when: ansible_system != "Win32NT"

- name: Create Fish functions directory for Unix
  ansible.builtin.file:
    mode: "755"
    owner: "{{ ansible_user_id }}"
    path: "{{ ansible_env.HOME }}/.config/fish/functions"
    state: directory
  when: ansible_system != "Win32NT"

- name: Copy Fish settings file for Unix
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    force: true
    mode: "644"
    owner: "{{ ansible_user_id }}"
    src: config.fish
  when: ansible_system != "Win32NT"

- name: Get installed Fish version
  ansible.builtin.command: fish --version
  changed_when: false
  register: fish_version_text
  when: ansible_system != "Win32NT"

- name: Parse Fish version
  ansible.builtin.set_fact:
    fish_version: >-
      {{ fish_version_text.stdout | regex_search('(\d+\.)+\d+') }}
  when: ansible_system != "Win32NT"

- name: Install Fisher package manager for Unix
  # prettier-ignore
  ansible.builtin.shell:  # noqa command-instead-of-module
    cmd: |
      curl -LSfs https://git.io/fisher | source
      fisher install jorgebucaran/fisher
    executable: "{{ fish_executable }}"
  changed_when: "'Installing jorgebucaran/fisher' in fish_fisher_install"
  register: fish_fisher_install
  when: >-
    ansible_system != "Win32NT" and fish_version is
    ansible.builtin.version("3.0", ">=")

- name: Install Bass Bash compatibility utility for Unix
  ansible.builtin.shell:
    cmd: |
      source {{ ansible_env.HOME }}/.config/fish/config.fish
      fisher install edc/bass
    executable: "{{ fish_executable }}"
  changed_when: "'Installing edc/bass' in fish_bass_install"
  register: fish_bass_install
  when: >-
    ansible_system != "Win32NT" and fish_version is
    ansible.builtin.version("3.0", ">=")

- name: Change user default shell to Fish for Unix
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ fish_executable }}"
  become: true
  when: ansible_system != "Win32NT"

- name: Mark role as executed to prevent reruns
  ansible.builtin.set_fact:
    cacheable: true
    fish_role_executed: true
