---
- name: Install Bash for FreeBSD
  become: true
  community.general.pkgng:
    name: bash
  when: ansible_system == "FreeBSD"

- name: Install Bash for Linux
  become: true
  package:
    name:
      - bash
      - bash-completion
  when: ansible_system == "Linux"

- name: Install Bash for MacOS
  community.general.homebrew:
    name:
      - bash
      - bash-completion
  when: ansible_system == "Darwin"

- name: Copy Bash non-login settings file for Unix
  copy:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    force: true
    mode: "754"
    owner: "{{ ansible_user_id }}"
    src: .bashrc
  when: ansible_system != "Win32NT"

- name: Copy Bash login settings file for Unix
  copy:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    force: true
    mode: "754"
    owner: "{{ ansible_user_id }}"
    src: .bash_profile
  when: ansible_system != "Win32NT"

- name: Copy shell aliases file for Unix
  copy:
    dest: "{{ ansible_env.HOME }}/.aliases"
    force: true
    mode: "754"
    owner: "{{ ansible_user_id }}"
    src: .aliases
  when: ansible_system != "Win32NT"
