---
# Certificate generation requires Certutil from the Nss package. For more
# information, visit https://github.com/FiloSottile/mkcert#installation.
- name: Install network security service libraries for Linux
  ansible.builtin.package:
    name: "{{ mkcert_dependencies[ansible_pkg_mgr] }}"
  become: true
  vars:
    mkcert_dependencies:
      apk: nss-tools
      apt: libnss3-tools
      dnf: nss-tools
      pacman: nss
  when: ansible_system == "Linux"

- name: Get latest Mkcert version
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/mkcert.json
  register: mkcert_formula
  when: ansible_system == "Linux"

- name: Install Mkcert for Linux
  ansible.builtin.get_url:
    dest: /usr/local/bin/mkcert
    mode: "755"
    url: >-
      https://github.com/FiloSottile/mkcert/releases/download/v{{
      mkcert_formula.json.versions.stable }}/mkcert-v{{
      mkcert_formula.json.versions.stable }}-linux-{{ system_architecture }}
  become: true
  when: ansible_system == "Linux"

- name: Install Mkcert for MacOS
  community.general.homebrew:
    name:
      - mkcert
      - nss
  when: ansible_system == "Darwin"

- name: Install Mkcert for Windows
  community.windows.win_scoop:
    name: mkcert
  when: ansible_system == "Win32NT"
