---
- name: Get latest GDU version
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/gdu.json
  register: gdu_formula
  when: ansible_system == "Linux"

- name: Install GDU for FreeBSD
  become: true
  community.general.pkgng:
    name: gdu
  when: ansible_system == "FreeBSD"

- name: Download GDU for Linux
  ansible.builtin.unarchive:
    dest: /tmp/
    mode: "777"
    remote_src: true
    src: >-
      https://github.com/dundee/gdu/releases/download/v{{
      gdu_formula.json.versions.stable }}/gdu_linux_{{ system_architecture
      }}.tgz
  become: true
  when: ansible_system == "Linux" and ansible_pkg_mgr != "apk"

- name: Install GDU for Linux
  ansible.builtin.copy:
    dest: /usr/local/bin/gdu
    mode: "755"
    src: /tmp/gdu_linux_{{ system_architecture }}
  become: true
  when: ansible_system == "Linux" and ansible_pkg_mgr != "apk"

- name: Install GDU for MacOS
  community.general.homebrew:
    name: gdu
  when: ansible_system == "Darwin"

- name: Install GDU for Windows
  community.windows.win_scoop:
    name: gdu
  when: ansible_system == "Win32NT"
