---
- name: Get latest Navi version
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/navi.json
  register: navi_formula
  when: ansible_system == "Linux"

- name: Install Navi for Linux
  ansible.builtin.unarchive:
    dest: /usr/local/bin/
    mode: "755"
    remote_src: true
    src: >-
      https://github.com/denisidoro/navi/releases/download/v{{
      navi_formula.json.versions.stable }}/navi-v{{
      navi_formula.json.versions.stable }}-x86_64-unknown-linux-musl.tar.gz
  become: true
  when: ansible_system == "Linux" and ansible_architecture == "x86_64"

- name: Install Navi for MacOS
  community.general.homebrew:
    name: navi
  when: ansible_system == "Darwin"

- name: Install Navi for Windows
  chocolatey.chocolatey.win_chocolatey:
    name: navi
  when: ansible_system == "Win32NT"
# Enable when Navi support noninteractive downloads.
#
# - name: Download Navi cheatsheets for Unix
#   ansible.builtin.command: navi repo add {{ item }}
#   loop: "{{ navi_repos }}"
#   when: ansible_system != "Win32NT"

# - name: Download Navi cheatsheets for Windows
#   ansible.builtin.win_command: navi repo add {{ item }}
#   loop: "{{ navi_repos }}"
#   when: ansible_system == "Win32NT"
