---
- name: Install Tailscale for FreeBSD
  become: true
  community.general.pkgng:
    name: tailscale
  tags:
    - install
  when: ansible_facts.system == "FreeBSD"

- name: Install Tailscale for Linux
  ansible.builtin.shell: # noqa command-instead-of-module
    cmd: curl -LSfs https://tailscale.com/install.sh | sh
    creates: /usr/bin/tailscale
  become: true
  tags:
    - install
  when: ansible_facts.system == "Linux" and systemd

- name: Install Tailscale for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: tailscale
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Install Tailscale for Windows
  community.windows.win_scoop:
    global: true
    name: tailscale
  tags:
    - install
  when: ansible_facts.system == "Win32NT"
