---
- name: Get latest Vagrant version
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/cask/vagrant.json
  register: vagrant_formula
  when: ansible_system == "Linux"

- name: Install Vagrant for FreeBSD
  become: true
  community.general.pkgng:
    name: vagrant
  when: ansible_system == "FreeBSD"

- name: Install Vagrant for Linux
  ansible.builtin.unarchive:
    dest: /usr/local/bin/
    group: root
    mode: "755"
    owner: root
    remote_src: true
    src: >-
      https://releases.hashicorp.com/vagrant/{{ vagrant_formula.json.version
      }}/vagrant_{{ vagrant_formula.json.version }}_linux_amd64.zip
  become: true
  when: ansible_system == "Linux" and ansible_architecture == "x86_64"

- name: Install Vagrant for MacOS
  community.general.homebrew_cask:
    accept_external_apps: true
    name: vagrant
    state: present
  when: ansible_system == "Darwin"

- name: Install Vagrant for Windows
  community.windows.win_scoop:
    name: vagrant
  when: ansible_system == "Win32NT"
