---
# AppImages requires FUSE.
- name: Install FUSE for Arch distributions
  become: true
  community.general.pacman:
    name: fuse3
  when: ansible_pkg_mgr == "pacman" and ansible_architecture == "x86_64"

- name: Create AppImages directory for Linux
  ansible.builtin.file:
    mode: "755"
    path: /usr/local/appimages
    owner: root
    state: directory
  become: true
  when: ansible_system == "Linux"

- name: Create AppImageLauncher settings directory for Linux
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/.config"
    mode: "755"
    owner: "{{ ansible_user_id }}"
    state: directory
  when: ansible_system == "Linux"

- name: Copy AppImageLauncher settings file for Linux
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.config/appimagelauncher.cfg"
    mode: "644"
    owner: "{{ ansible_user_id }}"
    src: appimagelauncher.cfg
  when: ansible_system == "Linux"

- name: Install AppImage packages for Linux
  ansible.builtin.get_url:
    dest: /usr/local/appimages/{{ item.name }}
    mode: "755"
    owner: root
    url: "{{ item.url }}"
  become: true
  loop: "{{ appimage_packages }}"
  when: ansible_system == "Linux"
