---
- name: Get latest Glow version
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/glow.json
  register: glow_formula
  when: ansible_system == "Linux" and ansible_pkg_mgr != "apk"

# TODO: Integrate once installation becomes stable.
# - name: Install Glow for Alpine
#   become: true
# community.general.apk:
#     name: glow
#     repository: http://dl-cdn.alpinelinux.org/alpine/edge/testing
#     state: latest
#     update_cache: true
#   when: ansible_pkg_mgr == "apk"

- name: Install Glow for FreeBSD
  become: true
  community.general.pkgng:
    name: glow
  when: ansible_system == "FreeBSD"

- name: Download Glow for Linux
  ansible.builtin.unarchive:
    dest: /tmp/
    mode: "755"
    remote_src: true
    src: >-
      https://github.com/charmbracelet/glow/releases/download/v{{
      glow_formula.json.versions.stable }}/glow_{{
      glow_formula.json.versions.stable }}_linux_{{
      glow_arch[system_architecture] }}.tar.gz
  become: true
  vars:
    glow_arch:
      amd64: x86_64
      arm64: arm64
  when: ansible_system == "Linux" and ansible_pkg_mgr != "apk"

- name: Install Glow for Linux
  ansible.builtin.copy:
    dest: /usr/local/bin/glow
    mode: "755"
    src: /tmp/glow
  become: true
  when: ansible_system == "Linux" and ansible_pkg_mgr != "apk"

- name: Install Glow for MacOS
  community.general.homebrew:
    name: glow
  when: ansible_system == "Darwin"

- name: Install Glow for Windows
  community.windows.win_scoop:
    name: glow
  when: ansible_system == "Win32NT"
