---
- name: Update packages for Alpine
  become: true
  community.general.apk:
    update_cache: true
    upgrade: true
  when: ansible_pkg_mgr == "apk"

- name: Update packages for Arch
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true
  when: ansible_pkg_mgr == "pacman"

- name: Update packages for Debian
  ansible.builtin.apt:
    autoremove: true
    update_cache: true
    upgrade: full
  become: true
  when: ansible_pkg_mgr == "apt"

- name: Update packages for Fedora
  ansible.builtin.dnf:
    autoremove: true
    # Updating all packages causes an error since dnf would be removed.
    # name: "*"
    update_cache: true
  become: true
  when: ansible_pkg_mgr == "dnf"

- name: Update packages for MacOS
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  when: ansible_system == "Darwin"
