---
- name: Get latest Mongo Shell version for Linux
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/mongosh.json
  register: mongosh_formula_linux
  when: ansible_system == "Linux"

- name: Get latest Mongo Shell version for Windows
  ansible.windows.win_uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/mongosh.json
  register: mongosh_formula_windows
  when: ansible_system == "Win32NT"

- name: Download Mongo Shell for Linux
  ansible.builtin.unarchive:
    dest: /tmp/
    mode: "755"
    remote_src: true
    src: >-
      https://downloads.mongodb.com/compass/mongosh-{{
      mongosh_formula_linux.json.versions.stable }}-linux-{{
      mongosh_arch[ansible_architecture] }}.tgz
  become: true
  vars:
    mongosh_arch:
      aarch64: arm64
      x86_64: x64
  when: ansible_system == "Linux" and ansible_pkg_mgr != "apk"

- name: Install Mongo Shell for Linux
  ansible.builtin.copy:
    dest: /usr/local/bin/mongosh
    mode: "755"
    src: >-
      /tmp/mongosh-{{ mongosh_formula_linux.json.versions.stable }}-linux-{{
      mongosh_arch[ansible_architecture] }}/bin/mongosh
  become: true
  vars:
    mongosh_arch:
      aarch64: arm64
      x86_64: x64
  when: ansible_system == "Linux" and ansible_pkg_mgr != "apk"

- name: Install Mongo Shell for MacOS
  community.general.homebrew:
    name: mongosh
  when: ansible_system == "Darwin"

- name: Install Mongo Shell for Windows
  ansible.windows.win_package:
    path: >-
      https://downloads.mongodb.com/compass/mongosh-{{
      mongosh_formula_windows.json.versions.stable }}-x64.msi
  when: ansible_system == "Win32NT"
