---
- name: Get latest Exa version
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/exa.json
  register: exa_formula
  when: ansible_system == "Linux"

- name: Install Exa for FreeBSD
  become: true
  community.general.pkgng:
    name: exa
  when: ansible_system == "FreeBSD"

- name: Download Exa for Linux
  ansible.builtin.unarchive:
    dest: /tmp/
    mode: "777"
    remote_src: true
    src: >-
      https://github.com/ogham/exa/releases/download/v{{
      exa_formula.json.versions.stable }}/exa-linux-x86_64-musl-v{{
      exa_formula.json.versions.stable }}.zip
  become: true
  when: ansible_system == "Linux" and system_architecture == "amd64"

- name: Install Exa for Linux
  ansible.builtin.copy:
    dest: /usr/local/bin/exa
    mode: "755"
    remote_src: true
    src: /tmp/bin/exa
  become: true
  when: ansible_system == "Linux" and system_architecture == "amd64"

- name: Install Exa for MacOS
  become: true
  become_user: "{{ user_id }}"
  community.general.homebrew:
    name: exa
  when: ansible_system == "Darwin"
