- name: Install Flatpak for Linux
  become: yes
  package:
    name: flatpak
    state: present
  when: ansible_system == "Linux"

- name: Add Flathub remote repository for Linux
  become: yes
  shell:
    cmd: >-
      flatpak remote-add --if-not-exists flathub
      https://flathub.org/repo/flathub.flatpakrepo
  when: ansible_system == "Linux"

- name: Install Flatpak packages for Linux
  become: yes
  community.general.flatpak:
    name: "{{ item }}"
  loop: "{{ flatpak_packages }}"
  when: ansible_system == "Linux"
