---
- name: Get latest DVC version
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/dvc.json
  register: dvc_formula
  when: ansible_system == "Linux"

- name: Install DVC for Debian distributions
  ansible.builtin.apt:
    deb: >-
      https://github.com/iterative/dvc/releases/download/{{
      dvc_formula.json.versions.stable }}/dvc_{{
      dvc_formula.json.versions.stable }}_amd64.deb
  become: true
  when: ansible_pkg_mgr == "apt" and system_architecture == "amd64"

- name: Install DVC for Fedora distributions
  ansible.builtin.dnf:
    disable_gpg_check: true
    name: >-
      https://github.com/iterative/dvc/releases/download/{{
      dvc_formula.json.versions.stable }}/dvc-{{
      dvc_formula.json.versions.stable }}-1.x86_64.rpm
  become: true
  when: ansible_pkg_mgr == "dnf" and system_architecture == "amd64"

- name: Install DVC for FreeBSD
  become: true
  community.general.pkgng:
    name: dvc
  when: ansible_system == "FreeBSD"

- name: Install DVC for MacOS
  community.general.homebrew:
    name: dvc
  when: ansible_system == "Darwin"

- name: Install DVC for Windows
  community.windows.win_scoop:
    name: dvc
  when: ansible_system == "Win32NT"
