---
- name: Get latest Xsv version
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/xsv.json
  register: xsv_formula
  when: ansible_system == "Linux"

- name: Install Xsv for FreeBSD
  become: true
  community.general.pkgng:
    name: xsv-rs
  when: ansible_system == "FreeBSD"

- name: Install Xsv for Linux
  ansible.builtin.unarchive:
    dest: /usr/local/bin
    mode: "755"
    remote_src: true
    src: >-
      https://github.com/BurntSushi/xsv/releases/download/{{
      xsv_formula.json.versions.stable }}/xsv-{{
      xsv_formula.json.versions.stable }}-x86_64-unknown-linux-musl.tar.gz
  become: true
  when: ansible_system == "Linux" and system_architecture == "amd64"

- name: Install Xsv for MacOS
  become: true
  become_user: "{{ user_id }}"
  community.general.homebrew:
    name: xsv
  when: ansible_system == "Darwin"

- name: Install Xsv for Windows
  community.windows.win_scoop:
    name: xsv
  when: ansible_system == "Win32NT"
