---
- name: Get latest Fzf version
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/fzf.json
  register: fzf_formula
  when: ansible_system == "Linux"

- name: Install FzF for FreeBSD
  become: true
  community.general.pkgng:
    name: fzf
  when: ansible_system == "FreeBSD"

# Fzf version from most Linux package managers is too outdated for compatibility
# with Navi and Fzf Fish plugin.
- name: Install Fzf for Linux
  ansible.builtin.unarchive:
    dest: /tmp/
    mode: "777"
    remote_src: true
    src: >-
      https://github.com/junegunn/fzf/releases/download/{{
      fzf_formula.json.versions.stable }}/fzf-{{
      fzf_formula.json.versions.stable }}-linux_{{ system_architecture }}.tar.gz
  become: true
  when: ansible_system == "Linux"

- name: Install Fzf for Linux
  ansible.builtin.copy:
    dest: /usr/local/bin/fzf
    mode: "755"
    remote_src: true
    src: /tmp/fzf
  become: true
  when: ansible_system == "Linux"

- name: Install FzF for MacOS
  community.general.homebrew:
    name:
      - fzf
      - tree
  when: ansible_system == "Darwin"

- name: Install FzF for Windows
  community.windows.win_scoop:
    name:
      - fzf
      - psfzf
  when: ansible_system == "Win32NT"

- name: Download Fzf Bash key bindings file for Unix
  ansible.builtin.get_url:
    dest: "{{ ansible_env.HOME }}/.fzf_key_bindings.bash"
    mode: "755"
    owner: "{{ ansible_user_id }}"
    url: https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.bash
  become: true
  when: ansible_system != "Win32NT"

- name: Create Fish functions directory for Unix
  ansible.builtin.file:
    mode: "755"
    owner: "{{ ansible_user_id }}"
    path: "{{ ansible_env.HOME }}/.config/fish/functions"
    state: directory
  when: ansible_system != "Win32NT"

- name: Download Fzf Fish key bindings file for Unix
  ansible.builtin.get_url:
    dest: "{{ ansible_env.HOME }}/.config/fish/functions/fzf_key_bindings.fish"
    mode: "755"
    owner: "{{ ansible_user_id }}"
    url: https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.fish
  become: true
  when: ansible_system != "Win32NT"

- name: Mark role as executed to prevent reruns
  ansible.builtin.set_fact:
    cacheable: true
    fzf_role_executed: true
