---
- name: Install Java for Alpine
  become: true
  community.general.apk:
    name:
      - maven
      - openjdk17
  when: ansible_pkg_mgr == "apk"

- name: Install Java for Arch
  become: true
  community.general.pacman:
    name:
      - jdk-openjdk
      - maven
  when: ansible_pkg_mgr == "pacman"

- name: Install Java for Debian
  ansible.builtin.apt:
    name:
      - maven
      - openjdk-17-jdk
  become: true
  when: ansible_pkg_mgr == "apt"

- name: Install Java for Fedora
  ansible.builtin.dnf:
    name:
      - java-latest-openjdk
      - maven
  become: true
  when: ansible_pkg_mgr == "dnf"

- name: Install Java for FreeBSD
  become: true
  community.general.pkgng:
    name:
      - maven
      - openjdk17
  when: ansible_system == "FreeBSD"

- name: Install Java for MacOS
  community.general.homebrew:
    name:
      - java
      - maven
      - openjdk
    state: present
  when: ansible_system == "Darwin"

- name: Install Java for Window
  community.windows.win_scoop:
    name:
      - maven
      - openjdk
  when: ansible_system == "Win32NT"

- name: Make Java discover OpenJDK on MacOS
  ansible.builtin.file:
    src: "{{ openjdk_path[system_architecture] }}"
    dest: /Library/Java/JavaVirtualMachines/openjdk.jdk
    force: true
    mode: "755"
    owner: "{{ ansible_user_id }}"
    state: link
  become: true
  vars:
    openjdk_path:
      amd64: /usr/local/opt/openjdk/libexec/openjdk.jdk
      arm64: /opt/homebrew/opt/openjdk/libexec/openjdk.jdk
  when: ansible_system == "Darwin"

- name: Create Java Jar directory for Linux
  ansible.builtin.file:
    mode: "755"
    path: /usr/local/share/java/jar/
    state: directory
  become: true
  when: ansible_system == "Linux"
