---
- name: Add Nvidia CUDA APT preferences for Ubuntu
  ansible.builtin.get_url:
    dest: /etc/apt/preferences.d/cuda-repository-pin-600
    mode: "644"
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
  become: true
  when: ansible_pkg_mgr == "apt" and system_architecture == "amd64"

- name: Download Nvidia CUDA repository key for Ubuntu
  ansible.builtin.get_url:
    dest: /tmp/cuda-archive-keyring.pub
    mode: "644"
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
  become: true
  when: ansible_pkg_mgr == "apt" and system_architecture == "amd64"

- name: Install Nvidia CUDA repository key for Ubuntu
  ansible.builtin.command: >-
    gpg --batch --dearmor --yes --output
    /usr/share/keyrings/cuda-archive-keyring.gpg /tmp/cuda-archive-keyring.pub
  become: true
  # Command does not provide stdout information to determine a change.
  changed_when: true
  when: ansible_pkg_mgr == "apt" and system_architecture == "amd64"

- name: Add Nvidia CUDA repository for Ubuntu
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/cuda.list
    force: true
    mode: "644"
    src: cuda.list.j2
  become: true
  when: ansible_pkg_mgr == "apt" and system_architecture == "amd64"

- name: Install Nvidia CUDA for Ubuntu
  ansible.builtin.apt:
    name: cuda
    update_cache: true
  become: true
  when: ansible_pkg_mgr == "apt" and system_architecture == "amd64"

- name: Install Nvidia CUDA for Windows
  community.windows.win_scoop:
    name: cuda
  when: ansible_system == "Win32NT"
