---
- name: Download Nvidia Docker repository key for Ubuntu
  ansible.builtin.get_url:
    dest: /tmp/nvidia-docker-archive-keyring.pub
    mode: "644"
    url: https://nvidia.github.io/nvidia-docker/gpgkey
  become: true
  when: ansible_pkg_mgr == "apt" and system_architecture == "amd64"

- name: Install Nvidia Docker repository key for Ubuntu
  ansible.builtin.command: >-
    gpg --batch --dearmor --yes --output
    /usr/share/keyrings/nvidia-docker-archive-keyring.gpg
    /tmp/nvidia-docker-archive-keyring.pub
  become: true
  # Command does not provide stdout information to determine a change.
  changed_when: true
  when: ansible_pkg_mgr == "apt" and system_architecture == "amd64"

- name: Add Nvidia Docker repository for Ubuntu distribution
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/nvidia-docker.list
    force: true
    mode: "644"
    src: nvidia-docker.list.j2
  become: true
  when: ansible_pkg_mgr == "apt" and system_architecture == "amd64"

- name: Install Nvidia Docker for Ubuntu
  ansible.builtin.apt:
    name: nvidia-docker2
    update_cache: true
  become: true
  when: ansible_pkg_mgr == "apt" and system_architecture == "amd64"
