---
- name: Install Deno for FreeBSD
  become: true
  community.general.pkgng:
    name: deno
  when: ansible_system == "FreeBSD"

# TODO: Add Deno Alpine install when supported. See
# https://github.com/denoland/deno/issues/3711 for status.
#
# TODO: Add Deno Linux ARM install when supported. See
# https://github.com/denoland/deno/issues/1846 for status.
- name: Download Deno installer for Unix
  ansible.builtin.get_url:
    dest: /tmp/deno_install.sh
    mode: "755"
    url: https://deno.land/x/install/install.sh
  when: >-
    ansible_system == "Darwin" or (ansible_system == "Linux" and ansible_pkg_mgr
    != "apk" and system_architecture == "amd64")

- name: Install Deno for Unix
  ansible.builtin.command: /tmp/deno_install.sh
  changed_when: "'installed successfully' in deno_install"
  register: deno_install
  when: >-
    ansible_system == "Darwin" or (ansible_system == "Linux" and ansible_pkg_mgr
    != "apk" and system_architecture == "amd64")

- name: Install Deno for Windows
  community.windows.win_scoop:
    name: deno
  when: ansible_system == "Win32NT"

- name: Create Fish completions directory for Unix
  ansible.builtin.file:
    mode: "755"
    owner: "{{ ansible_user_id }}"
    path: "{{ ansible_env.HOME }}/.config/fish/completions"
    state: directory
  when: ansible_system != "Win32NT"

- name: Generate Deno Fish completions for Unix
  ansible.builtin.shell: >-
    deno completions fish > {{ ansible_env.HOME
    }}/.config/fish/completions/deno.fish
  changed_when: true
  environment:
    PATH: "{{ ansible_env.HOME }}/.deno/bin:{{ ansible_env.PATH }}"
  when: >-
    ansible_system in ["Darwin", "FreeBSD"] or (ansible_system == "Linux" and
    ansible_pkg_mgr != "apk" and system_architecture == "amd64")

- name: Create Deno PowerShell completions directory for Windows
  ansible.windows.win_file:
    path: >-
      {{ ansible_env.HOME }}/Documents/WindowsPowerShell/Modules/DenoCompletion
    state: directory
  when: ansible_system == "Win32NT"

- name: Generate Deno PowerShell completions module for Windows
  ansible.windows.win_shell: >-
    deno completions powershell > {{ ansible_env.HOME
    }}/Documents/WindowsPowerShell/Modules/DenoCompletion/DenoCompletion.psm1
  when: ansible_system == "Win32NT"
