---
# TODO: Tmate is not yet available on stable Alpine. Check
# https://pkgs.alpinelinux.org/packages?name=tmate status.
- name: Install Tmux for Alpine
  become: true
  community.general.apk:
    name: tmux
  when: ansible_pkg_mgr == "apk"

- name: Install Tmux for FreeBSD
  become: true
  community.general.pkgng:
    name:
      - tmate
      - tmux
  when: ansible_system == "FreeBSD"

- name: Install Tmux for Linux
  ansible.builtin.package:
    name:
      - tmate
      - tmux
  become: true
  when: ansible_system == "Linux" and ansible_pkg_mgr != "apk"

- name: Install Tmux for MacOS
  community.general.homebrew:
    name:
      - tmate
      - tmux
  when: ansible_system == "Darwin"
