---
- name: Get latest SD version
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/sd.json
  register: sd_formula
  when: ansible_system == "Linux"

- name: Install SD for Alpine distributions
  become: true
  community.general.apk:
    name: sd
    repository: http://dl-cdn.alpinelinux.org/alpine/edge/testing
    state: latest
    update_cache: true
  when: ansible_pkg_mgr == "apk"

- name: Install SD for FreeBSD
  become: true
  community.general.pkgng:
    name: sd
  when: ansible_system == "FreeBSD"

- name: Install SD for Linux
  ansible.builtin.get_url:
    dest: /usr/local/bin/sd
    mode: "755"
    url: >-
      https://github.com/chmln/sd/releases/download/v{{
      sd_formula.json.versions.stable }}/sd-v{{ sd_formula.json.versions.stable
      }}-x86_64-unknown-linux-gnu
  become: true
  when: >-
    ansible_system == "Linux" and ansible_architecture == "x86_64" and
    ansible_pkg_mgr != "apk"

- name: Install SD for MacOS
  community.general.homebrew:
    name: sd
  when: ansible_system == "Darwin"

- name: Install SD for Windows
  community.windows.win_scoop:
    name: sd
  when: ansible_system == "Win32NT"
