---
- name: Install desktop management dependencies for MacOS
  community.general.homebrew:
    name: duti
  when: ansible_system == "Darwin"

- name: Change desktop settings for GNOME
  ansible.builtin.script: gnome.sh
  when: ansible_system == "Linux" and gnome_desktop

# Linux distributions with GNOME desktops should be configured after general
# GNOME settings in order to use overrides.
- name: Change desktop settings for Fedora
  ansible.builtin.script: fedora.sh
  when: ansible_pkg_mgr == "dnf" and gnome_desktop

- name: Change desktop settings for PopOS
  ansible.builtin.script: popos.sh
  when: ansible_system == "Linux" and desktop == "pop"

- name: Change desktop settings for Ubuntu
  ansible.builtin.script: ubuntu.sh
  when: ansible_system == "Linux" and desktop == "ubuntu"

- name: Change desktop settings for MacOS
  ansible.builtin.script: macos.sh
  when: ansible_system == "Darwin"

- name: Change desktop settings for Windows
  ansible.builtin.script: windows.ps1
  when: ansible_system == "Win32NT"

- name: Change desktop settings for XFCE
  ansible.builtin.script: xfce.sh
  when: ansible_system == "Linux" and desktop == "xfce"
