---
- name: Get latest Docker Compose version
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/docker-compose.json
  register: docker_compose_formula
  when: ansible_system == "Linux"

- name: Install Docker Compose for FreeBSD
  become: true
  community.general.pkgng:
    name: docker-compose
  when: ansible_system == "FreeBSD"

- name: Install Docker Compose for Linux
  ansible.builtin.package:
    name: docker-compose
  become: true
  when: ansible_system == "Linux"

- name: Create Docker Compose plugin directory for Linux
  ansible.builtin.file:
    mode: "755"
    owner: root
    path: /usr/lib/docker/cli-plugins
    state: directory
  become: true
  when: ansible_system == "Linux"

- name: Install Docker Compose plugin for Linux
  ansible.builtin.get_url:
    dest: /usr/lib/docker/cli-plugins/docker-compose
    mode: "755"
    owner: root
    url: >-
      https://github.com/docker/compose/releases/download/v{{
      docker_compose_formula.json.versions.stable }}/docker-compose-linux-{{
      ansible_architecture }}
  become: true
  when: ansible_system == "Linux"

- name: Install Docker Compose for MacOS
  community.general.homebrew:
    name: docker-compose
    state: present
  when: ansible_system == "Darwin"

- name: Install Docker Compose for Windows
  community.windows.win_scoop:
    name:
      - docker-compose
      - posh-docker
  when: ansible_system == "Win32NT"

- name: Create Fish completions directory for Unix
  ansible.builtin.file:
    mode: "755"
    owner: "{{ ansible_user_id }}"
    path: "{{ ansible_env.HOME }}/.config/fish/completions"
    state: directory
  when: ansible_system != "Win32NT"

- name: Install Docker Compose Fish shell completions for Unix
  ansible.builtin.get_url:
    dest: "{{ ansible_env.HOME }}/.config/fish/completions/docker-compose.fish"
    mode: "664"
    owner: root
    url: https://raw.githubusercontent.com/docker/compose/master/contrib/completion/fish/docker-compose.fish
  become: true
  when: ansible_system != "Win32NT"
