---
_ctrl_key: "{{ 'cmd' if ansible_system == 'Darwin' else 'ctrl' }}"
_vscode_arch:
  amd64: x64
  arm64: arm64
vscode_extensions:
  - "antfu.vite"
  - "bierner.markdown-mermaid"
  - "bungcip.better-toml"
  - "coolbear.systemd-unit-file"
  - "dbaeumer.vscode-eslint"
  - "denoland.vscode-deno"
  - "dorzey.vscode-sqlfluff"
  - "esbenp.prettier-vscode"
  - "foxundermoon.shell-format"
  - "golang.Go"
  - "hashicorp.terraform"
  - "james-yu.latex-workshop"
  - "jroesch.lean"
  - "ms-azuretools.vscode-docker"
  - "ms-kubernetes-tools.vscode-kubernetes-tools"
  - "ms-python.python"
  - "ms-vscode-remote.vscode-remote-extensionpack"
  - "RandomFractalsInc.vscode-data-preview"
  - "redhat.vscode-yaml"
  - "ritwickdey.liveserver"
  - "rust-lang.rust-analyzer"
  - "skyapps.fish-vscode"
  - "stkb.rewrap"
  - "sumneko.lua"
  - "tilt-dev.tiltfile"
  - "timonwong.shellcheck"
  - "vadimcn.vscode-lldb"
  - "vscode-icons-team.vscode-icons"
  - "vue.volar"
  - "yzhang.markdown-all-in-one"
