---
# TODO: Install Alacritty for Debian distributions.
- name: Add Alacritty PPA for Ubuntu distributions
  ansible.builtin.apt_repository:
    repo: ppa:mmstick76/alacritty
  become: true
  when: >-
    ansible_pkg_mgr == "apt" and deb_distro_base == "ubuntu" and
    ansible_distribution != "Pop!_OS" and ansible_architecture == "x86_64"

- name: Install Alacritty for FreeBSD
  become: true
  community.general.pkgng:
    name: alacritty
  when: ansible_system == "FreeBSD"

- name: Install Alacritty for Linux
  ansible.builtin.package:
    name: alacritty
  become: true
  when: ansible_system == "Linux" and ansible_pkg_mgr != "apt"

- name: Install Alacritty for MacOS
  community.general.homebrew_cask:
    accept_external_apps: true
    name: alacritty
    state: present
  when: ansible_system == "Darwin"

- name: Install Alacritty for Ubuntu distributions
  ansible.builtin.apt:
    name: alacritty
  become: true
  when: >-
    ansible_pkg_mgr == "apt" and deb_distro_base == "ubuntu" and
    ansible_architecture == "x86_64"

- name: Install Alacritty for Windows
  community.windows.win_scoop:
    name: alacritty
  when: ansible_system == "Win32NT"

- name: Create Alacritty configuration directory for Unix
  ansible.builtin.file:
    mode: "755"
    owner: "{{ ansible_user_id }}"
    path: "{{ ansible_env.HOME }}/.config/alacritty/"
    state: directory
  when: ansible_system != "Win32NT"

- name: Create Alacritty configuration directory for Windows
  ansible.windows.win_file:
    path: "{{ ansible_env.HOME }}/AppData/Roaming/alacritty/"
    state: directory
  when: ansible_system == "Win32NT"

- name: Copy Alacritty configuration file for Unix
  ansible.builtin.template:
    dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml"
    force: true
    mode: "644"
    owner: "{{ ansible_user_id }}"
    src: alacritty.j2
  when: ansible_system != "Win32NT"

- name: Copy Alacritty configuration file for Windows
  ansible.windows.win_template:
    dest: "{{ ansible_env.HOME }}/AppData/Roaming/alacritty/alacritty.yml"
    force: true
    src: alacritty.j2
  when: ansible_system == "Win32NT"
