---
- name: Get latest Duf version
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/duf.json
  register: duf_formula
  when: ansible_pkg_mgr in ["apt", "zypper"]

- name: Install Duf for Alpine
  become: true
  community.general.apk:
    name: duf
    repository: http://dl-cdn.alpinelinux.org/alpine/edge/testing
    state: latest
    update_cache: true
  when: ansible_pkg_mgr == "apk"

# On some Debian systems, Duf is available as an APT package.
- name: Install Duf for Debian via APT
  ansible.builtin.apt:
    name: duf
  become: true
  ignore_errors: true
  register: duf_apt
  when: ansible_pkg_mgr == "apt"

- name: Install Duf for Debian via GitHub
  ansible.builtin.apt:
    deb: >-
      https://github.com/muesli/duf/releases/download/v{{
      duf_formula.json.versions.stable }}/duf_{{
      duf_formula.json.versions.stable }}_linux_{{ system_architecture }}.deb
  become: true
  when: ansible_pkg_mgr == "apt" and duf_apt is failed

- name: Install Duf for FreeBSD
  become: true
  community.general.pkgng:
    name: duf
  when: ansible_system == "FreeBSD"

- name: Install Duf for Linux
  ansible.builtin.package:
    name: duf
  become: true
  when: >-
    ansible_system == "Linux" and ansible_pkg_mgr not in ["apk", "apt",
    "zypper"]

- name: Install Duf for MacOS
  community.general.homebrew:
    name: duf
  when: ansible_system == "Darwin"

- name: Install Duf for Suse
  become: true
  community.general.zypper:
    disable_gpg_check: true
    name: >-
      https://github.com/muesli/duf/releases/download/v{{
      duf_formula.json.versions.stable }}/duf_{{
      duf_formula.json.versions.stable }}_linux_{{ system_architecture }}.rpm
  when: ansible_pkg_mgr == "zypper"

- name: Install Duf for Windows
  community.windows.win_scoop:
    name: duf
  when: ansible_system == "Win32NT"
