---
- name: Install Pacman packages for Arch distributions
  become: true
  community.general.pacman:
    name: "{{ item }}"
  loop: "{{ pacman_packages }}"
  when: ansible_pkg_mgr == "pacman"

- name: Install Apt packages by name for Debian distributions
  ansible.builtin.apt:
    name: "{{ item }}"
  become: true
  loop: "{{ apt_packages }}"
  when: ansible_pkg_mgr == "apt" and "/" not in item

- name: Install Apt packages by path for Debian distributions
  ansible.builtin.apt:
    deb: "{{ item }}"
  become: true
  loop: "{{ apt_packages }}"
  when: ansible_pkg_mgr == "apt" and "/" in item

- name: Install DNF packages for Fedora distributions
  ansible.builtin.dnf:
    name: "{{ item }}"
  become: true
  loop: "{{ dnf_packages }}"
  when: ansible_pkg_mgr == "dnf"

- name: Install Pkg packages for FreeBSD
  become: true
  community.general.pkgng:
    name: "{{ item }}"
  loop: "{{ pkg_packages }}"
  when: ansible_system == "FreeBSD"

- name: Install Homebrew casks for MacOS
  community.general.homebrew_cask:
    accept_external_apps: true
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_casks }}"
  when: ansible_system == "Darwin"

- name: Install Homebrew packages for MacOS
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_packages }}"
  when: ansible_system == "Darwin"

- name: Install build tools with Chocolatey for Windows
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item }}"
  loop: "{{ chocolatey_packages }}"
  when: ansible_system == "Win32NT"

- name: Install Scoop packages for Windows
  community.windows.win_scoop:
    name: "{{ item }}"
  loop: "{{ scoop_packages }}"
  when: ansible_system == "Win32NT"
