---
- name: Get latest Zellij version
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/zellij.json
  register: zellij_formula
  when: ansible_system == "Linux"

- name: Download Zellij for Linux
  ansible.builtin.unarchive:
    dest: /usr/local/bin
    mode: "755"
    remote_src: true
    src: >-
      https://github.com/zellij-org/zellij/releases/download/v{{
      zellij_formula.json.versions.stable }}/zellij-{{ ansible_architecture
      }}-unknown-linux-musl.tar.gz
  become: true
  when: ansible_system == "Linux"

- name: Install Zellij for MacOS
  community.general.homebrew:
    name: zellij
  when: ansible_system == "Darwin"

- name: Create Zellij settings directory for Unix
  ansible.builtin.file:
    mode: "755"
    owner: "{{ ansible_user_id }}"
    path: "{{ ansible_env.HOME }}/.config/zellij"
    state: directory
  when: ansible_system in ["Darwin", "Linux"]

- name: Copy Zellij settings file for Unix
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.config/zellij/config.kdl"
    force: true
    mode: "644"
    owner: "{{ ansible_user_id }}"
    src: config.kdl
  when: ansible_system in ["Darwin", "Linux"]

- name: Create Fish completions directory for Unix
  ansible.builtin.file:
    mode: "755"
    owner: "{{ ansible_user_id }}"
    path: "{{ ansible_env.HOME }}/.config/fish/completions"
    state: directory
  when: ansible_system in ["Darwin", "Linux"]

- name: Install Zellij Fish completion for Unix
  ansible.builtin.shell:
    cmd: >-
      zellij setup --generate-completion fish > {{ ansible_env.HOME
      }}/.config/fish/completions/zellij.fish
  when: ansible_system in ["Darwin", "Linux"]
